### PR TITLE
Contributions from the work EmNet has done to enhance Controls

### PR DESCRIPTION
**Pull request by rkertesz**

### CODE REVIEW

**Comment by samhatchett** [comment]
Been thinking more about the GPL/BSD issue - and I really don't think it makes sense to have a bifurcated license with different levels of permissiveness depending on which branch we're in. Maybe deserves some more offline discussion to really understand your motivations -- but i doubt i could be dissuaded. Very strong preference that the repo and all additions are licensed under BSD-2. However in saying this i realize that the current master is not licensed at all... which should be fixed also.

**Comment by rkertesz** [comment]
That is fine. Let me know when you license everything and then I can change the license for our contribution to match the preference of the existing OWA group. At a recent presentation, a colleague pointed people to the OWA repo to get to the enhanced control rules so we are fully committed. 

Our rationale to-date for using a less permissive license was because we didn't see a defined mechanism by which contributions could progress towards integration into an official EPA release (which was the driving goal behind our OSS effort). As such, in the event that it wasn't integrated into EPA SWMM, it was desirable to receive attribution for the work we have done (particularly if used by a commercial vendor). That said, we recognize the issues faced when trying to license SWMM as L/GPL (particularly with existing commercial vendors). Thank you for following up and keeping this project moving along.

**Comment by samhatchett** [comment]
i've added the BSD-2 license file to the repo root - my research tells me that this is enough. You can merge in that commit from MASTER, strip the license text from the new files, and update your pull request. If you prefer to keep some reference to the license in your source files, then let's make it a one- or two-line comment that references the license file rather than duplicating the full text.

not an emergency yet, but we will eventually need to have Contributor License Agreements and a Contributors.txt file to document all of the work that will inevitably be done.

**Comment by samhatchett** [comment]
oh, and -- the Readme.md file in this pull is not a full description of SWMM - can we borrow language from EPA to more fully describe it, or perhaps summarize the official description of the software?

**Comment by bemcdonnell** [comment]
I'm preparing to migrate everything over to the new forked repo from USEPA (once I fully figure out the process :) ).  I am going to accept this pull request into the rpn_controls branch.  I think we're about due for an update meeting - hopefully before the end of the week

**Pull request merged**
